.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH weather 1 "NOV 2020" Weather "User Manuals"
.SH "NAME"
weather \- download Trafikverket weather station data
.
.SH "SYNOPSIS"
.B weather
.RB [ \-T
.IR seconds ]
.RB [ \-h
.IR duration ]
.B \-k
.I key
.I station
.br
.B weather
.RB [ \-T
.IR seconds ]
.RB [ \-h
.IR duration ]
.B \-k
.I key
.I station
.I file
.br
.B weather
.RB [ \-T
.IR seconds ]
.RB [ \-h
.IR duration ]
.B \-k
.I key
.B \-C
.I dir
.I station
\&...
.br
.B weather --help
.br
.B weather --version
.
.SH "DESCRIPTION"
.
.B weather
downloads data for one or more of Trafikverket's weather stations
and translates it to the format specified by
.BR weather (5).
There are three variations:
.
.IP \- 3x
Download from
.I station
and print to standard output.
.
.IP \-
Download from
.I station
and append to
.IR file .
.
.IP \-
Download from several listed stations
.I station
\&...
and append to corresponding files
.I dir/station
\&...
.
.PP
The data is typically one hour's worth of samples from Trafikverket's
.B WeatherObservation
data set, typically (always?) spaced ten minutes apart.
.PP
To use
.BR weather ,
you need to register with Trafikverket and generate an
API key.
You also need to know the station identifier, like
.I 1433
(a station in M\(:olndal).
.IP
The stations have longer names, too; 1433 is also known as
.IR SE_STA_VVIS1433 .
The short, all-numerical identifier is the one to use here.
.
.SH "OPTIONS"
.
.BP \-T\ \fIseconds
Socket timeout, to avoid waiting forever on a non-responsive server.
Defaults to 60 seconds: in early 2019,
the server is fairly slow, and regularly needs 20 seconds or more to respond.
.
.BP \-h\ \fIduration
Download data from the latest
.I duration
hours instead of just the latest hour.
.IR 32 ,
.I 32h
and
.I 1d8h
all mean the same thing.
.IP
You can not download years of data; the event horizon is probably
measured in days or weeks.
.
.BP \-k\ \fIkey
The API key.
.
.BP \-C\ \fIdir
The directory to use when saving to file(s) named by station identifier.
.
.BP --help
Print a brief help text and exit.
.
.BP --version
Print version information and exit.
.
.SH "EXIT CODE"
Non-zero if no correct samples were collected and saved.
.
.SH "NOTES"
.
The full response from the server is not preserved, only the data
which maps to
.BR weather (5).
Depending on the sensors of the weather station,
there may be plenty of discarded, more or less interesting, data.
.PP
I didn't choose mandatory
.IR https ;
Trafikverket did.
Personally I don't see a risk that someone spoofs my weather data,
or a privacy problem if someone learns that I'm interested in the weather.
.PP
At least some stations, some of the time, don't give
.I Precipitation.TotalWaterEquivalent
for snow.  When that happens, the output says that it snowed,
but not whether there were a few flakes or a full snow storm.
.
.SH "AUTHOR"
.
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
Thanks to Patrik for pointing out that this data set exists.
.
.SH "LICENSE"
The Modified BSD license (also known as the 3-clause BSD license).
.
.SH "SEE ALSO"
.
.BR weather (5),
.IR \[fo]https://api.trafikinfo.trafikverket.se/\[fc] .
