.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH weather_week 1 "JAN 2019" Weather "User Manuals"
.SH "NAME"
weather_week \- plot weekly weather data
.
.SH "SYNOPSIS"
.B weather_week
.RB [ \-p
.IR N ]
.RB [ \-o
.IR image-file ]
.I file
\&...
.br
.B weather_week --help
.br
.B weather_week --version
.
.SH "DESCRIPTION"
.
.B weather_week
reads
.BR weather (5)
data and renders the current week's temperature graph.
The graph is rendered in
.I \s-1SVG\s0
format. It's intended to be immediately readable, but not necessarily
detailed or very accurate.
What's plotted is:
.
.BP temperature
Air temperature; not the road temperature, which may also be available.
.
.BP rain\ and\ snow
Also known as precipitation.
The input data distinguishes rain, snow, sleet and so on, but here I
just show the amount.  It's unclear what the scale is, but you can tell
the difference between light and hard rain.
.
.BP wind
The mean wind force over ten minutes, and
(less distinctly) the max wind force over the past half hour,
if these are available in the input.
.
.BP wind\ direction
Printed as text (in Swedish) during periods with a stable, prevailing
wind direction.
Note that the direction data from
.I Trafikverket
seems to be of questionable quality: I've never seen it record wind from
the southwest so far.
.
.PP
For other data that's not plotted, see
.BR weather (5).
.
.PP
The input files may contain data from several locations, in which case you
get several overlayed graphs.
This is useful if you're really interested in another, nearby location:
you're reminded of the inevitable errors involved.
.PP
Wind direction is picked from the first location only.
.
.SH "OPTIONS"
.
.BP \-p\ \fIN
Render a previous week instead of the current one:
.B \-p1
for the past week,
.B \-p2
for two weeks ago, and so on.
.
.BP \-o\ \fIimage-file
The name of the image file to write.  If none is provided,
the image is written to standard output.
.
.BP --help
Print a brief help text and exit.
.
.BP --version
Print version information and exit.
.
.
.SH "NOTES"
.
A week is defined as Monday\-Sunday, since that's how we think about
weeks in Sweden nowadays.
.
.SH "AUTHOR"
.
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
.
.SH "LICENSE"
The Modified BSD license (also known as the 3-clause BSD license).
.
.SH "SEE ALSO"
.
.BR weather (5),
.BR weather (1).
