.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH weather 5 "NOV 2020" Weather "User Manuals"
.
.SH "NAME"
weather \- weather observations file format
.
.SH "DESCRIPTION"
.
A weather observation, or meteorology observation, or weather sample file
is a set of samples from a single place, at different times.
The sampled data includes e.g. temperature and wind speed.
.PP
In reality, the file format is designed for the data provided by
.IR Trafikverket ,
who have weather stations along the roads in Sweden,
and who allow public (but not anonymous) HTTPS-based access to the data.
.
.
.SH "BASIC SYNTAX"
.
The file format is a line-oriented text file format.
Allowed text encodings are
.BR UTF-8 ,
.B "ISO\ 8859-1"
(Latin-1) and (by extension)
.BR ASCII .
.PP
Blank lines and comment lines, introduced by a
.BR # ,
are ignored.
All other lines are fields, on the form
.IP
.B "name: value"
.PP
Whitespace is allowed, except before the field name.
.PP
The actual content is a series of timestamped
.BR samples ,
from a single weather station.  A sample starts with a
.B date
field and continues to the next sample.
Samples need not be ordered by time \- although keeping them
ordered is good policy.
No fields are mandatory, and the fields may vary between samples.
.
.SS "Fields"
.
.de TRV
.br
\s-2[\\$*]\s0
..
.
For each field, I list what it maps to in Trafikverket's
.I WeatherObservation
model.
There is a very similar mapping to their older
.IR WeatherStation ,
too.
With some other data source, the meaning of any field might be slightly
different; for example, perhaps one measures max wind speed over 20 minutes.
Another factor, probably at least as important, is the quality and characteristics
of the sensors used.
.
.BP date 18x
Sample time, in ISO format, with offset from GMT.
For example,
.IR "2022-11-27T\:23:05:03.001\:+01:00" .
The milliseconds are, of course, nonsense.
.IP
In older data, perhaps before schema version 2,
the timezone appears to be implied Swedish local time
(and thus ambiguous when daylight savings time ends in fall).
.TRV "Sample"
.
.BP temperature.road
Road temperature, in degrees centigrade.
.TRV "Surface/Temperature"
.
.BP temperature.air
Air temperature.
.TRV "Air/Temperature"
.
.BP wind.direction
Wind direction, in degrees.  For example, 270 means wind
.I from
the west, 0 from the north.
.TRV "Wind/Direction"
.
.BP wind.force
Wind force, in meters/second.
Mean value over ten minutes.
.TRV "Wind/Speed"
.
.BP wind.force.max
Max wind force during the past 30 minutes.
.TRV "Aggregated30minutes/Wind/SpeedMax"
.
.BP rain.amount
Numeric precipitation, in millimeters per hour.
.TRV "Aggregated10minutes/Precipitation/TotalWaterEquivalent"
.
.BP rain.type
One of
.BR none ,
.BR rain ,
.BR snow ,
.BR other .
Trafikverket currently flags rain and snow independently;
.B other
tends to mean a mix of both, or perhaps a change from one to the other
during a ten-minute period.
.TRV "Aggregated10minutes/Precipitation/{Rain,Snow}"
.
.BP humidity
Relative humidity, in percent.
.TRV "Air/RelativeHumidity"
.
.
.SH "EXAMPLE"
.IP
.ft CW
.nf
date: 2020-11-17T11:50:00+01:00
temperature.road:   7.8
temperature.air :   7.8
humidity        :  93.8
wind.direction  :   180
wind.force      :   4.9
wind.force.max  :   7.9
rain.amount     :   0.2
rain.type       :  rain
.fi
.
.SH "AUTHOR"
J\(:orgen Grahn \fI\[fo]grahn+src@snipabacken.se\[fc]
.
.
.SH "SEE ALSO"
.
.IR \[fo]https://api.trafikinfo.trafikverket.se/\[fc] .
