.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH weather 5 "JAN 2019" Weather "User Manuals"
.
.SH "NAME"
weather \- weather observations file format
.
.SH "DESCRIPTION"
.
A weather observation, or meteorology observation, or weather sample file
is a set of samples from a single place, at different times.
The sampled data includes e.g. temperature and wind speed.
.PP
In reality, the file format is designed for the data provided by
.IR Trafikverket ,
who have weather stations along the roads in Sweden,
and who allow public HTTP-based access to the data.
.
.
.SH "BASIC SYNTAX"
.
The file format is a line-oriented text file format.
Allowed text encodings are
.BR UTF-8 ,
.B "ISO\ 8859-1"
(Latin-1) and (by extension)
.BR ASCII .
.PP
Blank lines and comment lines, introduced by a
.BR # ,
are ignored.
All other lines are fields, on the form
.IP
.B "name: value"
.PP
Whitespace is allowed, except before the field name.
.PP
The actual content is a series of timestamped
.BR samples ,
from a single weather station.  A sample starts with a
.B date
field and continues to the next sample.
Samples need not be ordered by time \- although keeping them
ordered is good policy.
No fields are mandatory, and the fields may vary between samples.
.
.SS "Fields"
.
.BP date 18x
Sample time, in ISO format. The timezone appears to be Swedish local time
(and thus ambiguous when daylight savings time ends in fall).
.
.BP temperature.road
Road temperature, in degrees centigrade.
.
.BP temperature.air
Air temperature.
.
.BP wind.direction
Wind direction, in degrees.  For example, 270 means wind
.I from
the west, 0 from the north.
.
.BP wind.force
Wind force, in meters/second.
Mean value over ten minutes.
.
.BP wind.force.max
Max wind force during the past 30 minutes.
.
.BP rain.amount
Numeric precipitation, in millimeters per hour.
.
.BP rain.type
One of
.BR none ,
.BR rain ,
.BR snow ,
.BR other .
Trafikverket has, like the Eskimos, more types. Their
.I duggregn
and
.I regn
map to
.BR rain ;
hail, sleet and so on map to
.BR other .
.
.BP humidity
Relative humidity, in percent.
.
.
.SH "EXAMPLE"
.IP
.ft CW
.nf
date: 2018-09-27T00:30:01
temperature.air : 10.9
temperature.road:  9.3
wind.force      :  7.4
wind.force.max  : 12.6
wind.direction  :  270
humidity        : 78.8
.fi
.
.SH "AUTHOR"
J\(:orgen Grahn \fI\[fo]grahn+src@snipabacken.se\[fc]
.
.
.SH "SEE ALSO"
.
.IR \[fo]https://api.trafikinfo.trafikverket.se/\[fc] .
